### ISSUE TITLE
[-] Wrong HTTP file format.  

### ISSUE THREAD

**Issue by chezis45** [enjoiz/XXEinjector#10]
Tried every example I can find that states the correct format.  Here is a sample file: 
POST /blind/submitDetails.php HTTP/1.1
Host: 10.129.201.94
Content-Length: 169
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)
Content-Type: text/plain;charset=UTF-8
Accept: */*
Origin: http://10.129.201.94
Referer: http://10.129.201.94/blind/
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Connection: close

<?xml version="1.0" encoding="UTF-8"?>
XXEINJECT

**Comment by enjoiz** [comment]
I have verified your request and it works. Probably some whitespace character. Try to export working request directly from proxy tool.

**Comment by monofloyed** [comment]
I had a the same error. Double check the directory file path your using is where your saving the file, and have the proper xml tag for the header.
