### ISSUE TITLE
can't run

### ISSUE THREAD

**Issue by pkhadka56** [enjoiz/XXEinjector#2]
#ruby XXEinjector.rb --host=127.0.0.1 --path=/etc --file=/tmp/test.xml --ssl

XXEinjector.rb:238:in `block in <main>': undefined method `chomp' for nil:NilClass (NoMethodError)
	from XXEinjector.rb:237:in `loop'
	from XXEinjector.rb:237:in `<main>'

**Comment by enjoiz** [comment]
Please read how request file should look like in the second issue "Need a demo". Then specify correct file in "file" argument.
