### ISSUE TITLE
XXEinjector.rb: end of file reached (EOFError)

### ISSUE THREAD

**Issue by infosecsecurity** [enjoiz/XXEinjector#4]
Got this new error

**Comment by enjoiz** [comment]
Right now I do not see where the error occured. If you want help you need also to paste you request file. In my opinion it is still your invalid request file. It needs to be valid, correctly formatted HTTP request.

**Comment by infosecsecurity** [comment]
Thanks for your time
[phprequest.txt](https://github.com/enjoiz/XXEinjector/files/910135/phprequest.txt)

**Comment by enjoiz** [comment]
Cannot replicate. Works for me without issues. I just corrected formatting and changed GET to POST as it contains body:
![err](https://cloud.githubusercontent.com/assets/12471904/24867187/b0862c3e-1e0c-11e7-99bc-2c2b06189648.png)
Please use valid HTTP request file and it will work.
